### PR TITLE
Support gh community dark

### PR DESCRIPTION
**Pull request by the-j0k3r**
what it sayz on ze tin

needs doing the tag/releases for this also, giz me access and ill do it too:)

### CODE REVIEW

**Comment by Mottie** [comment]
Awesome, thanks!

**Comment by silverwind** [comment]
> giz me access

I invited you on the org, I think you deserved it. Once you accept, you'll have write access on pretty much all our repos. Please continue to open PRs for possible controversial changes, otherwise you can commit straightforward things directly.

**Comment by the-j0k3r** [comment]
Of course, you should expect that :) thx.

I dont see an invite excpet the one I had for GHCD from Mottie

**Comment by the-j0k3r** [comment]
I see it now, :) accepted :)

**Comment by silverwind** [comment]
Check on the https://github.com/StylishThemes page.

**Pull request merged**
